<?php
/**
 * Display and manage users
 *
 * Copyright (C) 2011-2013 Holger Schletz <holger.schletz@web.de>
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 */

$headers = array(
    'Id' => $this->translate('Login name'),
    'FirstName' => $this->translate('First name'),
    'LastName' => $this->translate('Last name'),
    'MailAddress' => $this->translate('Mail address'),
    'edit' => '',
    'delete' => '',
);

$formats = array(
    'edit' => 'text',
    'delete' => 'text',
);

$renderCallbacks = array(
    'MailAddress' => 'renderMailAddress',
    'edit' => 'renderEdit',
    'delete' => 'renderDelete',
);

function renderMailAddress($view, $account)
{
    $address = $account->getMailAddress();
    if ($address) {
        return $view->htmlTag(
            'a',
            $view->escape($address),
            array(
                'href' => 'mailto:' . urlencode($address),
            ),
            true
        );
    }
}

function renderEdit($view, $account)
{
    return $view->htmlTag(
        'a',
        $view->translate('Edit'),
        array(
            'href' => $view->standardUrl(
                array(
                    'controller' => 'accounts',
                    'action' => 'edit',
                    'id' => $account->getId(),
                )
            )
        ),
        true
    );
}

function renderDelete($view, $account)
{
    if ($account->getId() == Zend_Auth::getInstance()->getIdentity()) {
        return '';
    } else {
        return $view->htmlTag(
            'a',
            $view->translate('Delete'),
            array(
                'href' => $view->standardUrl(
                    array(
                        'controller' => 'accounts',
                        'action' => 'delete',
                        'id' => $account->getId(),
                    )
                )
            ),
            true
        );
    }
}

print $this->table(
    $this->accounts,
    array(),
    $headers,
    $formats,
    'Model_Account',
    null,
    $renderCallbacks
);

print $this->htmlTag(
    'p',
    $this->htmlTag(
        'a',
        $this->translate('Add user'),
        array('href' => $this->baseUrl() . '/accounts/add')
    ),
    array('class' => 'textcenter')
);
