<?php
/**
 * Display general information about a group
 *
 * $Id$
 *
 * Copyright (C) 2011-2013 Holger Schletz <holger.schletz@web.de>
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 */

$group = $this->group;
print $this->groupHeader($group);

print "<dl>\n";

print $this->htmlTag(
    'dt',
    $this->translate('Name')
);
print $this->htmlTag(
    'dd',
    $this->escape($group->getName())
);

print $this->htmlTag(
    'dt',
    $this->translate('ID')
);
print $this->htmlTag(
    'dd',
    $group->getId()
);

print $this->htmlTag(
    'dt',
    $this->translate('Description')
);
print $this->htmlTag(
    'dd',
    $this->escape($group->getDescription())
);

print $this->htmlTag(
    'dt',
    $this->translate('Creation date')
);
print $this->htmlTag(
    'dd',
    $this->escape($group->getCreationDate())
);

print $this->htmlTag(
    'dt',
    $this->translate('SQL query')
);
print $this->htmlTag(
    'dd',
    $this->htmlTag(
        'code',
        $this->escape($group->getDynamicMembersSql())
    )
);

print "</dl>\n";
