<?php
/**
 * Display and install packages associated with a group
 *
 * $Id$
 *
 * Copyright (C) 2011-2013 Holger Schletz <holger.schletz@web.de>
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 */

$group = $this->group;

print $this->groupHeader($group);

print $this->htmlTag(
    'h2',
    $this->translate('Associated packages')
);

$headers = array(
    'Name' => $this->translate('Name'),
    'remove' => '',
);

$formats = array(
    'remove' => 'text',
);

$renderCallbacks = array(
    'remove' => 'renderRemoveLink',
);

function renderRemoveLink($view, $package)
{
    return $view->htmlTag(
        'a',
        $view->translate('remove'),
        array(
            'href' => $view->BaseUrl()
                     . '/group/removepackage/name/'
                     . urlencode($package->getName())
                     . '/id/'
                     . $view->group->getId()
        ),
        true
    );
}

print $this->table(
    $group->getPackages($this->direction),
    null,
    $headers,
    $formats,
    'Model_Package',
    null,
    $renderCallbacks
);


// Display package installation form if packages are available
$form = new Form_AffectPackages();
if ($form->addPackages($this->group)) {
    $form->setAction($this->baseUrl() . '/group/installpackage');
    print $this->htmlTag(
        'h2',
        $this->translate('Install packages')
    );
    print $form;
}
