<?php
/**
 * Display standard error page
 *
 * $Id$
 *
 * Copyright (C) 2011 Holger Schletz <holger.schletz@web.de>
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 */
?>
  <h1>An error occurred</h1>
  <h2><?php print $this->message ?></h2>

  <?php if ('development' == APPLICATION_ENV): ?>

  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> <?php print $this->escape($this->exception->getMessage()) ?>
  </p>

  <h3>Stack trace:</h3>
  <pre><?php print $this->escape($this->exception->getTraceAsString()) ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?php print $this->escape(var_export($this->request->getParams(), true)) ?>
  </pre>
  <?php endif;
