<?php
/**
 * Display display information
 *
 * $Id$
 *
 * Copyright (C) 2011-2013 Holger Schletz <holger.schletz@web.de>
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 */

$computer = $this->computer;

print $this->inventoryHeader($computer);


// Display display controllers

$headers = array(
    'Name' => $this->translate('Name'),
    'Chipset' => $this->translate('Chipset'),
    'Memory' => $this->translate('Memory'),
    'CurrentResolution' => $this->translate('Current resolution'),
);

$renderCallbacks = array (
    'Chipset' => 'renderValues',
    'Memory' => 'renderValues',
    'CurrentResolution' => 'renderValues',
);

function renderValues($view, $object, $property)
{
    $value = $view->escape($object->getProperty($property));
    if (!$value) {
        $value = '&ndash;';
    } else {
        if ($property == 'Memory') {
            $value .= '&nbsp;MB';
        }
    }
    return $value;
}

$controllers = $this->getHelper('table')->table(
    $computer->getChildObjects('DisplayController'),
    null,
    $headers,
    array(),
    'Model_DisplayController',
    null,
    $renderCallbacks,
    $numControllers
);

if ($numControllers) {
    print $this->htmlTag(
        'h2',
        $this->translate('Display controllers')
    );
    print $controllers;
}


// Display display devices

$headers = array(
    'Manufacturer' => $this->translate('Manufacturer'),
    'Description' => $this->translate('Description'),
    'Serial' => $this->translate('Serial number'),
    'ProductionDate' => $this->translate('Production date'),
    'Type' => $this->translate('Type'),
);

$renderCallbacks = array (
);

$displays = $this->getHelper('table')->table(
    $computer->getChildObjects('Display'),
    null,
    $headers,
    array(),
    'Model_Display',
    null,
    array(),
    $numDisplays
);

if ($numDisplays) {
    print $this->htmlTag(
        'h2',
        $this->translate('Displays')
    );
    print $displays;
}
