<?php
/**
 * Display network information
 *
 * Copyright (C) 2011-2014 Holger Schletz <holger.schletz@web.de>
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 */

$computer = $this->computer;

print $this->inventoryHeader($computer);


// Display global network settings

print "<dl>\n";

print $this->htmlTag(
    'dt',
    $this->translate('DNS server')
);
print $this->htmlTag(
    'dd',
    $this->escape($computer->getDnsServer())
);

print $this->htmlTag(
    'dt',
    $this->translate('Default gateway')
);
print $this->htmlTag(
    'dd',
    $this->escape($computer->getDefaultGateway())
);

print "</dl>\n";


// Display netwok interfaces if present

$headers = array(
    'Description' => $this->translate('Description'),
    'Rate' => $this->translate('Data rate'),
    'MacAddress' => $this->translate('MAC address'),
    'IpAddress' => $this->translate('IP address'),
    'Netmask' => $this->translate('Netmask'),
    'Gateway' => $this->translate('Gateway'),
    'DhcpServer' => $this->translate('DHCP server'),
    'Status' => $this->translate('Status'),
);

$renderCallbacks = array(
    'MacAddress' => 'renderMacAddress',
);

function renderMacAddress($view, $interface)
{
    $mac = $view->escape($interface->getMacAddress()->getAddressWithVendor());
    if ($interface->isBlacklisted()) {
        return "<span class='gray'>$mac</span>";
    } else {
        return $mac;
    }
}

$interfaces = $this->getHelper('table')->table(
    $computer->getChildObjects('NetworkInterface'),
    null,
    $headers,
    array(),
    'Model_NetworkInterface',
    null,
    $renderCallbacks,
    $numInterfaces
);

if ($numInterfaces) {
    print $this->htmlTag(
        'h2',
        $this->translate('Network interfaces')
    );
    print $interfaces;
}


// Display modems if present

$headers = array(
    'Type' => $this->translate('Type'),
    'Name' => $this->translate('Name'),
);

$renderCallbacks = array(
);

$modems = $this->getHelper('table')->table(
    $computer->getChildObjects('Modem'),
    null,
    $headers,
    array(),
    'Model_Modem',
    null,
    array(),
    $numModems
);

if ($numModems) {
    print $this->htmlTag(
        'h2',
        $this->translate('Modems')
    );
    print $modems;
}
