<?php
/**
 * Display inventoried registry keys
 *
 * Copyright (C) 2011-2013 Holger Schletz <holger.schletz@web.de>
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 */

$computer = $this->computer;

print $this->inventoryHeader($computer);


$headers = array(
    'Value' => $this->translate('Value'),
    'Data' => $this->translate('Content'),
);

$formats = array(
    'Value' => 'text',
);

$renderCallbacks = array(
    'Value' => 'renderValue',
);

function renderValue($view, $data, $property)
{
    return $view->escape($data->getValue()->getName());
}

$data = $this->getHelper('table')->table(
    $computer->getChildObjects('RegistryData', $this->order, $this->direction),
    null,
    $headers,
    $formats,
    'Model_RegistryData',
    null,
    $renderCallbacks,
    $numKeys
);

if ($numKeys) {
    print $this->htmlTag(
        'h2',
        $this->translate('Registry Keys')
    );
    print $data;
}

print $this->htmlTag(
    'p',
    $this->htmlTag(
        'a',
        $this->translate('Manage inventoried values'),
        array('href' => $this->baseUrl() . '/preferences/registryvalues'),
        true
    ),
    array('class' => 'textcenter')
);
