<?php
/**
 * Display Windows-specific information
 *
 * Copyright (C) 2011-2015 Holger Schletz <holger.schletz@web.de>
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 */

$computer = $this->computer;
$windows = $this->windows;

print $this->inventoryHeader($computer);

print "<dl>\n";

print $this->htmlTag(
    'dt',
    $this->translate('Company')
);
print $this->htmlTag(
    'dd',
    $this->escape($windows->getCompany())
);

print $this->htmlTag(
    'dt',
    $this->translate('Owner')
);
print $this->htmlTag(
    'dd',
    $this->escape($windows->getOwner())
);

print $this->htmlTag(
    'dt',
    $this->translate('Product ID')
);
print $this->htmlTag(
    'dd',
    $this->escape($windows->getProductId())
);

print $this->htmlTag(
    'dt',
    $this->translate('Product key (reported by agent)')
);
print $this->htmlTag(
    'dd',
    $this->escape($windows->getProductKey())
);

print "</dl>\n";

// Print product key form if supported.
if (isset($this->form)) {
    print $this->form;
}
