<?php
/**
 * HTML page template
 *
 * $Id$
 *
 * Copyright (C) 2011,2012 Holger Schletz <holger.schletz@web.de>
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

echo $this->doctype();
?>

<html>

<head>
<?php
echo $this->headMeta();
echo "\n";
echo $this->headTitle();
echo "\n";
echo $this->HeadLink()->appendStylesheet($this->baseUrl('style.css'));
echo "\n";
echo $this->headStyle();
echo "\n";
echo $this->headScript();
?>

</head>

<body onload="if (typeof(init) == 'function') init()">

<div id="content">
<?php echo $this->layout()->content; ?>
</div>

<?php if (Zend_Auth::getInstance()->hasIdentity()): ?>

<div id="menu">
<?php
$menu = $this->navigation()->menu();
// Top level menu
echo $menu->renderMenu(
    null,
    array(
        'maxDepth' => 0,
        'ulClass' => 'navigation'
    )
);

if (Zend_Registry::isRegistered('subNavigation')) {
    $navigation = Zend_Registry::get('Zend_Navigation');
    echo $menu->renderMenu(
        $navigation->findOneByLabel(Zend_Registry::get('subNavigation')),
        array(
            'ulClass' => 'navigation navigation_sub',
        )
    );
} else {
    // Submenu of active branch, if present
    echo $menu->renderMenu(
        null,
        array(
            'ulClass' => 'navigation navigation_sub',
            'minDepth' => 1,
            'onlyActiveBranch' => true,
            'renderParents' => false,
        )
    );
}
?>

<div id="logout">
<?php echo '<a href="'
    . $this->baseUrl()
    . '/login/logout">'
    . $this->translate('Logout')
    . '</a>'
; ?>

</div>

</div>
<?php endif; ?>

</body>

</html>
